### ISSUE TITLE
targeting Android 12

### ISSUE THREAD

**Issue by EMI-INDO** [itsSoufianeDev/cordova-plugin-startapp-ads#2]
@itsSoufianeDev 

please upgrade the plugin targeting android 12

Please provide your paypal Email for us to give some money

**Comment by itsSoufianeDev** [comment]
I apologize for the delayed response.

The plugin now works for **Android 12** (SDK 31+)

Bear in mind that I kept this repo public to make it easy for me to integrate it in my cordova projects, and it's not meant to be used directly by other developers.

If you plan to use it, Clone it on your computer and change the **APPLICATION_ID** value in plugin.xml
`<meta-data android:name="com.startapp.sdk.APPLICATION_ID" android:value="your_app_id_here" />`

then add it to your cordova project like so:
`cordova plugin add "C:\Projects\path\to\plugin\cordova-plugin-startapp-ads"`

I will be launching soon a cordova/capacitor plugin for Start.io (StartApp) which will be well maintained.

That is it, Happy coding.
