### ISSUE TITLE
Need to hide splash loading image while app launch

### ISSUE THREAD

**Issue by ambikapathiperumal** [itsSoufianeDev/cordova-plugin-startapp-ads#3]
After disabling splash ads, Loading splash screen not hiding. It always showing while launching app in mobile.

**Comment by itsSoufianeDev** [comment]
Hi @ambikapathiperumal, issue fixed on version [1.3.1](https://github.com/itsSoufianeDev/cordova-plugin-startapp-ads/releases/tag/1.3.1)
